### ISSUE TITLE
Undefined index notice

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/EDD-Discount-Widget#11]
When saving an instance of this widget, if the "Hide Expiration" checkbox is left empty, I'm getting an undefined index notice:

```
PHP Notice:  Undefined index: hide_exp in \plugins\edd-discount-widget\edd-discount-widget.php on line 98
```

**Comment by rwebster85** [comment]
This is already fixed in 1.0.3 branch :)

https://github.com/easydigitaldownloads/EDD-Discount-Widget/issues/8
