### ISSUE TITLE
Method for retrieving discounts needs to be rewritten

### ISSUE THREAD

**Issue by dimadin** [awesomemotive/EDD-Discount-Widget#2]
`EDD_Discounts_Widget::get_discounts()` needs full rewrite. Looks like it doesn't work, but in any case it doesn't do any check so it throws notices and fatals even when you add it. Especially important with widgets block editor which does live preview.

**Comment by rwebster85** [comment]
I've started working on this one. Need to have a little think about the best way forward, since we need to handle the live preview as well as static output.
